# Generated by Django 3.2.8 on 2023-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100,
                 null=True, verbose_name='Nombres')),
                ('edad', models.IntegerField(null=True, verbose_name='Edad')),
                ('foto', models.ImageField(null=True,
                 upload_to='imagenes/', verbose_name='Foto')),
                ('vacuna', models.CharField(
                    max_length=100, null=True, verbose_name='vacuna')),
            ],
        ),
    ]
