# Generated by Django 3.2.8 on 2023-04-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombres')),
                ('edad', models.IntegerField(null=True, verbose_name='Edad')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto')),
                ('vacuna', models.ManyToManyField(to='mascotas.vacuna')),
            ],
        ),
    ]
