# Generated by Django 3.2.8 on 2023-04-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='vacuna',
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacuna',
            field=models.CharField(max_length=100, null=True, verbose_name='vacuna'),
        ),
    ]
