# Generated by Django 3.2.8 on 2023-04-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_auto_20230427_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vacuna',
        ),
    ]
