# Generated by Django 3.2.8 on 2023-04-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_vacunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='relacion',
            field=models.ManyToManyField(to='mascotas.vacunas'),
        ),
    ]
